"""Fix database revision state and add court scheduling tables

Revision ID: 0040d6d4e2cd
Revises: c1d2e3f4a5b6
Create Date: 2026-05-18 19:22:27.523085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0040d6d4e2cd'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'day_of_week', name='uq_court_schedule_day')
    )
    op.create_index(op.f('ix_court_schedules_id'), 'court_schedules', ['id'], unique=False)
    op.create_table('booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'slot_date', 'start_time', name='uq_booking_slot')
    )
    op.create_index('idx_court_availability', 'booking_slots', ['court_id', 'is_available'], unique=False)
    op.create_index('idx_court_date', 'booking_slots', ['court_id', 'slot_date'], unique=False)
    op.create_index(op.f('ix_booking_slots_id'), 'booking_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_slots_id'), table_name='booking_slots')
    op.drop_index('idx_court_date', table_name='booking_slots')
    op.drop_index('idx_court_availability', table_name='booking_slots')
    op.drop_table('booking_slots')
    op.drop_index(op.f('ix_court_schedules_id'), table_name='court_schedules')
    op.drop_table('court_schedules')
    # ### end Alembic commands ###
